# Generated by Django 4.2.7 on 2025-12-13 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chess_game', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='challenge',
            unique_together=set(),
        ),
    ]
